language: python
python: 
  - '3.6'
install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  # install in batch mode i.e. no input
  - bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/conda
  - export PATH="$HOME/conda/bin:$PATH"
  # clear bash cache table
  - hash -r
  - conda config --set always_yes yes
  - conda config --set changeps1 no
  - conda update -q conda
  - conda config --add channels conda-forge
  - conda config --set channel_priority strict
  - conda env create -q -f hazimp.yml python=$TRAVIS_PYTHON_VERSION
  - source activate hazimp
script:
  - nosetests -v
