#!/bin/bash
# First, purge all .pyc files to clean the source tree,
# in case some modules were deleted or removed.

find . -name "*.pyc" -delete

pylint hazimp  --disable=RP0401 --disable=RP0001 --disable=RP0002 --disable=RP0003 --disable=RP0101 --disable=RP0101 --disable=RP0701 #--disable=RP0801

mpirun -n 2 -mca btl ^openib nosetests examples/ --with-doctest `find examples/ -name 'test_*.py'` --cover-package=hazimp --with-xunit --xunit-file='nosetests.xml' --nocapture
# --nocapture let standard out go to standard out

mpirun -n 2 -mca btl ^openib nosetests tests/ --with-doctest `find tests/ -name 'test_*.py'` --cover-package=hazimp --with-xunit --xunit-file='nosetests.xml' --nocapture

pep8 .

# autopep8 hazimp_preprocessing/curve_data/*.py --in-place --aggressive
# autopep8 hazimp/*.py --in-place --aggressive
# autopep8 hazimp/*/*.py --in-place --aggressive
# autopep8 examples/*/*.py --in-place --aggressive
