#!/bin/bash
# First, purge all .pyc files to clean the source tree,
# in case some modules were deleted or removed.

find . -name "*.pyc" -delete

nosetests hazimp/ --with-doctest `find hazimp/ -name 'test_*.py'` --with-xunit --xunit-file='nosetests.xml' --nocapture
# --nocapture let standard out go to standard out

mpirun -n 2 nosetests hazimp/ --with-doctest `find hazimp/ -name 'test_*.py'` --with-xunit --xunit-file='nosetests.xml' --nocapture

# The scenario tests
nosetests examples/ --with-doctest `find examples/ -name 'test_*.py'` --with-xunit --xunit-file='nosetests.xml' --nocapture

mpirun -n 2 nosetests examples/ --with-doctest `find examples/ -name 'test_*.py'` --with-xunit --xunit-file='nosetests.xml' --nocapture
# --nocapture let standard out go to standard out

# This works on my PC
#nosetests hazimp/ --with-doctest --cover-package=hazimp --with-xunit --xunit-file='nosetests.xml' --nocapture