#!/bin/bash
# First, purge all .pyc files to clean the source tree,
# in case some modules were deleted or removed.

find . -name "*.pyc" -delete

nosetests tests/ --with-doctest `find tests/ -name 'test_*.py'` --with-coverage  --cover-package=hazimp --with-xunit --xunit-file='nosetests.xml' --nocapture
# --nocapture let standard out go to standard out

# This works on my PC
#nosetests tests/ --with-doctest --cover-package=hazimp --with-xunit --xunit-file='nosetests.xml' --nocapture
