#!/bin/bash
# First, purge all .pyc files to clean the source tree,
# in case some modules were deleted or removed.

find . -name "*.pyc" -delete

pylint curve_data  --disable=RP0401 --disable=RP0001 --disable=RP0002 --disable=RP0003 --disable=RP0101 --disable=RP0101 --disable=RP0701

nosetests curve_data/ --with-doctest `find curve_data/ -name 'test_*.py'` --cover-package=hazimp --with-xunit --xunit-file='nosetests.xml' --nocapture
# --nocapture let standard out go to standard out

pep8 .
