# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit tests for HazImp

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  Hazimp:
    name: Test HazImp
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up environment
      uses: conda-incubator/setup-miniconda@v2.0.0
      with:
        activate-environment: hazimp
        environment-file: hazimp.yml
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false

    - name: Test with nose
      shell: bash -l {0}
      run: |
        nosetests -v --exe
        nosetests examples/ --with-doctest -v

    - uses: codecov/codecov-action@v2
      with:
        env_vars: OS,PYTHON
        files: ./coverage.xml
