# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit tests for HazImp

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  Hazimp:
    name: Test HazImp
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up environment
      uses: conda-incubator/setup-miniconda@v2.0.0
      with:
        activate-environment: hazimp
        environment-file: hazimp.yml
        python-version: 3.6
        auto-activate-base: false
    - name: Install flake8 and pytest
      run: | 
        python -m pip install --upgrade pip
        pip install flake8 pytest
        echo "::add-path::/home/runner/.local/bin"
        echo ${PATH}
    - name: Test with nose
      shell: bash -l {0}
      run: |
        nosetests -v --exe
