# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout      
      uses: actions/checkout@v2

    - name: Update Conda environment with hazimp.yml
      uses: goanpeca/setup-miniconda@v1
      with:
        auto-activate-base: true
        auto-update-conda: true
        activate-environment: hazimp
        environment-file: hazimp.yml
    - name: Test environment
      shell: bash
      run: |
        pwd
        conda init
        conda activate hazimp
        conda info
    - name: Test with nosetests
      shell: bash
      run: nosetests -v
