# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update Conda environment with hazimp.yml
      uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        environment-file: hazimp.yml
        activate-environment: hazimp
    - name: Flake8 test
      run: flake8 .
    - name: Test with nosetests
      run: nosetests -v
