# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Update Conda environment with hazimp.yml
      uses: matthewrmshin/conda-action@v1
      with:
        args: conda env update -f ./hazimp.yml
    - name: Test with nosetests
      uses: matthewrmshin/conda-action@v1
      run: 
        nosetests
